---
title: "Dashboard and Synthesis"
format: 
  revealjs:
    embed-resources: true
editor: visual
---

## Goals

- Use skills developed over the semester to analyze the ice-off data in more detail
- Construct a dashboard that displays the data and analysis


## What is a dashboard?

- A dashboard is website or document that uses graphs, tables, and other visual elements to represent data and analyses.  
- A dashboard has an audience and should support decision-making


## Principles of building a dashboard

- Keep it Simple and Intuitive
- Use Consistent Design Elements
- Prioritize Information

::: aside
<https://medium.com/@mokkup/8-essential-dashboard-design-principles-for-effective-data-visualization-40653c5fd135>
:::


## Principles of building a dashboard

- Make it Responsive
- Use White Space Effectively
- Use Consistent Layout

::: aside
<https://medium.com/@mokkup/8-essential-dashboard-design-principles-for-effective-data-visualization-40653c5fd135>
:::


## Principles of building a dashboard

- Design for Speed
- Keep the Dashboard Updated
- Maintain Data Accuracy and Source Reliability

::: aside
<https://medium.com/@mokkup/8-essential-dashboard-design-principles-for-effective-data-visualization-40653c5fd135>
:::

## Dashboards in Quarto

- Quarto has a output type called a dashboard
- Built around the concept of "cards" in columns and rows
- Able to be easily deployed to a website
- Same approach as the Quarto documents we have used

## Dashboards in Quarto

```
---
title: "Sunapee Ice-off Dashboard"
format: 
  dashboard:
    embed-resources: true
---

## Row {height="20%"}

ADD CHUCK (CARD)

### Column 

ADD CHUCK (CARD)

### Column
```

## Science question

- How are lake-ice across the globe is changing over time?
- Use all the lakes in the lake-ice off dataset (from Module 3)

## Assignment

- `assignmment/assignment.md` is the introduction for the assignment
- `assignmment/dashboard.qmd` is the template that will complete for the assignment
- `tutorial/example-dashboard.qmd` is a simple example dashboard

## Assignment

-  Building "cards" for a dashboard
-  Most use tidyverse function covered in class where they can be used